version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=loan_management.settings
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: loan_management
      POSTGRES_USER: kshitiz
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
